spring.application.name=demo
spring.datasource.url=jdbc:mysql://localhost:3306/event_ticket_db
spring.datasource.username=root
spring.datasource.password=1234
spring.jpa.show-sql=true

# --- DATABASE STRATEGY ---
# STEP 1: Use 'create' for your FIRST run to generate the dummy data.
# STEP 2: After running successfully, change this to 'update' to protect your data!
spring.jpa.hibernate.ddl-auto=create